### ISSUE TITLE
nittro.github.io

### ISSUE THREAD

**Issue by f3l1x** [nittro/nittro-web#1]
Mozna by nebylo spatne udelat to jako Github page a vyuzit CNAME pro oficialni web.

Just say`in. 

:-)

**Comment by jahudka** [comment]
Jak to myslis presne? Ted to bezi na mym serveru, deploy z tohohle repository. Na github page umi bejt php backend? A jakej cname a kam? :-)

**Comment by f3l1x** [comment]
Jenom napad.

Viz tady: https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/
1. Ze by jsi prejmenoval nitrro-web na nittro.github.io, pripadne na nittro.org (bude to lepsi pri vyhledavani)
2. Pokud to pouzijes jako `nittro.github.io`, tak:
   1. Staci pridat soubor CNAME s obsahem `https://nittro.org` a je to.
   2. Kdokoli pak prijde na `nittro.github.io`, tak ho to prehodi na `nittro.org` a vsechno mas v 1 repozitari

**Comment by jahudka** [comment]
Porad tomu uplne nerozumim :-) tohle je dobry afaik k tomu, kdyz chci pouzit github pages, ale mit svoji domenu - ja ale nechci pouzit github pages, protoze na nich jen tezko rozchodim nette..? A vyhledavani ceho? Jakoby ten web ma repo na githubu protoze je to prakticky mit web v gitu a git je prakticky mit na githubu, ale normalne to ma slouzit proste jako public web, lidi nemaj najit jeho _repozitar_, ale ten web jako takovej, proto jsou vsude odkazy na nittro.org misto na github.com/nittro/nittro-web.. Promin, jsem v tom nejakej ztracenej, vubec se nejak nejsem schopnej zorientovat v tom, co vlastne navrhujes a v cem je to uzitecny :D

**Comment by f3l1x** [comment]
V pohode, asi to popisuju blbe. At to jde.

**Comment by jahudka** [comment]
Promiň, já celou noc nespal, jsem trochu mimo.. Podívám se na to znovu až se vyspím :-)
